package language.frontend

/**
 * Base class for frontend parsers. Contains functions for consuming tokens generated by the passed tokenizer.
 */
open class AbstractParser(private val tokenizer: Tokenizer) {
    val currentPosition
        get() = next.position

    var next = tokenizer.next()
        private set
    var lookahead = tokenizer.next()
        private set

    protected fun at(type: TokenType) = next.type == type

    protected fun expect(type: TokenType): Token {
        if (!at(type))
            error("expected $type, got ${next.type} at ${next.position}")
        return pop()
    }

    protected fun expect(vararg types: TokenType) {
        for (type in types) {
            expect(type)
        }
    }

    protected fun accept(type: TokenType) = at(type).also { if (it) pop() }

    protected fun pop() = next.also {
        next = lookahead
        lookahead = tokenizer.next()
    }

    protected fun unexpected(): Nothing = error("Unexpected token $next")

    protected fun error(msg: String): Nothing = throw ParseError(msg)
}

class ParseError(message: String) : Exception(message)